### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [mrpalbano/prj-rev-bwfs-dasmoto#6]
**GRADE**: Needs Improvement

**SUMMARY**: Good start on this project. With a couple small tweaks, the site will be looking great. Nice work keeping the html and css neat and consistently indented throughout. Also, good job using the divs and classes to help structure the content on the page.

Behind the scenes in the css, try to always keep in mind DRY principles. Avoid setting the same styling many times for similarly styled elements wherever possible. Additionally, make sure each line you're adding serves a purpose on the page. Lean, concise code is crucial and only becomes more so as your projects grow in size and complexity.

As a next step try saving your image files locally to an images folder inside of resources and then using relative file paths to link to those from your html and css. The link to css on line 5 of your html is a great example and more info can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/).

Keep up the good work!

**Comment by mrpalbano** [comment]
Thanks for all of the feedback! I'm trying to learn as much as I can through the program, so all of this is quite helpful (still pretty new with all of this).
